### PR TITLE
fix: improve button a11y

### PR DESCRIPTION
**Pull request by nolanlawson**
Improves the contrast ratio on the button from 2.62 to 7 (AAA).

Before:

Screenshot from 2022-11-12 07-08-43

After:

Screenshot from 2022-11-12 07-07-04

### CODE REVIEW

**Review by mlcdf — APPROVED** [review]

**Comment by mlcdf** [comment]
Yup, this is much better!

**Comment by mgifford** [comment]
Yes, that's great https://contrast-ratio.com/#%23141414-on-%23AE91E8

Much easier for everyone to see.

**Comment by nolanlawson** [comment]
Screenshot from 2022-11-12 10-54-08

Notifications as well ^

**Comment by nolanlawson** [comment]
Fixed for Mastodon v4

**Pull request merged**
